version: '3.8'
services:
  konv-mysql-database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: konv-mini-pipeline
    ports:
      - "3306:3306"
    volumes:
      - ./create_database.sql:/docker-entrypoint-initdb.d/1.sql
